name: hoha
on:
  push:
    branches:
      #     helsdksdfdsa
      - "release/[0-9]+.[0-9].[^0]"
      - "release/[0-9]+.[^0].[0-9]"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  speak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run echo
        run: echo ${{ github.ref }}
      - name: Run echo
        run: echo ${{ github.ref_name }}
