name: hoha
on:
  push:
    branches:
      - "release/[0-9]+.[0-9]+.^[1-9]+[0-9]*$"
  workflow_dispatch:

jobs:
  speak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run echo
        run: echo "Hello, World!"
